name: Push image tag latest to GitHub Container Registry

on:
  push:
    branches: [ "main" ]
    paths:
      - 'dockerfile'
      - 'download_dotnet.sh'
      - 'download_server.sh'
      - 'entrypoint.sh'
      - '.github/workflows/deploy-to-ghcr.io.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'dockerfile'
      - 'download_dotnet.sh'
      - 'download_server.sh'
      - 'entrypoint.sh'
      - '.github/workflows/deploy-to-ghcr.io.yml'

env:
  PLATAFORM_ARCH: linux/amd64
  
jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.PLATAFORM_ARCH }}
                
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile
          platforms: ${{ env.PLATAFORM_ARCH }}
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
